server:
  port: 8083
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ceng453group10
    password: mozanLOVESburgers58^^
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  main:
    banner-mode: off
  datasource:
    username: user10
    password: 6MfZn588r9
    url: jdbc:mariadb://144.122.71.168:3306/database10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
